### ISSUE TITLE
symbolic logo

### ISSUE THREAD

**Issue by tomerdo** [tomerdo/mamtak-frontend#12]
a symbolic logo that we would put on the main component

**Comment by Shahar1335** [comment]
![final_logo](https://user-images.githubusercontent.com/15312055/30912331-c677bf2c-a394-11e7-8a6c-3b7d40f02312.jpg)
![final_logo_bigger](https://user-images.githubusercontent.com/15312055/30912333-c9baefb0-a394-11e7-9545-167b5b5f81a0.jpg)

**Comment by tomerdo** [comment]
@assafdev
