### ISSUE TITLE
rest request in the client

### ISSUE THREAD

**Issue by tomerdo** [tomerdo/mamtak-frontend#15]
getting the data from the service - the service take the data from http request from the server

**Comment by Shahar1335** [comment]
node_modules/angular-in-memory-web-api/backend.service.d.ts(19,24): error TS1005: '=' expected.
node_modules/angular-in-memory-web-api/backend.service.d.ts(19,31): error TS1005: ';' expected.
node_modules/angular-in-memory-web-api/backend.service.d.ts(19,52): error TS1005: '(' expected.
