### ISSUE TITLE
block screen - showing an image

### ISSUE THREAD

**Issue by tomerdo** [tomerdo/mamtak-frontend#5]
block screen component

**Comment by tomerdo** [comment]
@AdiSh01 
תן פה כמה מילים איפה אנחנו עומדים.
מדריכים טובים שנתקלת בהם

**Comment by AdiSh01** [comment]
@tomerdo ברגע שאני אמצא מדריך שאצליח לגלות דרכו איך מציגים תמונה אני אוכל להגיד עליו שהוא באמת טוב :)

כרגע אני חוקר, אח"כ חוזר לכתוב וברגע שיעבוד או שתהיה פריצת דרך אני אעדכן
